export const GET_LOCALE_WEATHER_DATA_REQUEST =
    "GET_LOCALE_WEATHER_DATA_REQUEST";
export const GET_LOCALE_WEATHER_DATA_SUCCESS =
    "GET_LOCALE_WEATHER_DATA_SUCCESS";

export const SELECTED_DATE_REQUEST = "SELECTED_DATE_REQUEST";
export const SELECTED_DATE_SUCCESS = "SELECTED_DATE_SUCCESS";

export const GET_WEEK_WEATHER_DATA_REQUEST = "GET_WEEK_WEATHER_DATA_REQUEST";
export const GET_WEEK_WEATHER_DATA_SUCCESS = "GET_WEEK_WEATHER_DATA_SUCCESS";
